'use client';

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/model.gltf
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import useScrollPosition from '@/hooks/useScrollPosition';
import { useFrame } from '@react-three/fiber';

const Model = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('../models/model.gltf')
  const { isScrolling } = useScrollPosition();
  const { page } = props;

  const { actions } = useAnimations(animations, group)
  const [ animation, setAnimation ] = useState('pose');
  
  useEffect(() => {
    if( page === 'home') {
      setAnimation('sitting');
    }
  }, [])
  

  useFrame((state, delta) => {
    if( page === 'blog' && isScrolling ) {
      group.current.rotation.y = group.current.rotation.y += 0.005
    }
  })

  useEffect(() => {
    if(page !== 'home') {
      if (isScrolling) {
        setAnimation('swim')
      } else {
        setAnimation('pose')
      }
    }
    
  }, [isScrolling])

  useEffect(() => {
    // 애니메이션 변경 시작 & 종료 fadeIn/Out 처리
    actions[animation].reset().fadeIn(0.3).play();

    return () => actions[animation] && actions[animation].fadeOut(0.3);
  }, [animation])


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Chloe" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh scale={100} rotation={[-Math.PI / 2, 0, 0]} castShadow name="Chloe_body_lower" geometry={nodes.Chloe_body_lower.geometry} material={materials['매테리얼.003']} skeleton={nodes.Chloe_body_lower.skeleton} />
          <skinnedMesh scale={100} rotation={[-Math.PI / 2, 0, 0]} castShadow name="Chloe_body_shoes_L" geometry={nodes.Chloe_body_shoes_L.geometry} material={materials['매테리얼.003']} skeleton={nodes.Chloe_body_shoes_L.skeleton} />
          <skinnedMesh scale={100} rotation={[-Math.PI / 2, 0, 0]} castShadow name="Chloe_body_shoes_R" geometry={nodes.Chloe_body_shoes_R.geometry} material={materials['매테리얼.003']} skeleton={nodes.Chloe_body_shoes_R.skeleton} />
          <skinnedMesh scale={100} rotation={[-Math.PI / 2, 0, 0]} castShadow name="Chloe_body_upper" geometry={nodes.Chloe_body_upper.geometry} material={materials['매테리얼.003']} skeleton={nodes.Chloe_body_upper.skeleton} />
          <skinnedMesh scale={100} rotation={[-Math.PI / 2, 0, 0]} castShadow name="Chloe_hair_back_01" geometry={nodes.Chloe_hair_back_01.geometry} material={materials['hair.001']} skeleton={nodes.Chloe_hair_back_01.skeleton} />
          <skinnedMesh scale={100} rotation={[-Math.PI / 2, 0, 0]} castShadow name="Chloe_hair_bangs_02" geometry={nodes.Chloe_hair_bangs_02.geometry} material={materials['hair.001']} skeleton={nodes.Chloe_hair_bangs_02.skeleton} />
          <skinnedMesh scale={100} rotation={[-Math.PI / 2, 0, 0]} castShadow name="Chloe_hair_side_04" geometry={nodes.Chloe_hair_side_04.geometry} material={materials['hair.001']} skeleton={nodes.Chloe_hair_side_04.skeleton} />
          <skinnedMesh scale={100} rotation={[-Math.PI / 2, 0, 0]} castShadow name="Chloe_head_eyebrows" geometry={nodes.Chloe_head_eyebrows.geometry} material={materials['lambert1.002']} skeleton={nodes.Chloe_head_eyebrows.skeleton} />
          <skinnedMesh scale={100} rotation={[-Math.PI / 2, 0, 0]} castShadow name="Chloe_head_eyes_L_ball" geometry={nodes.Chloe_head_eyes_L_ball.geometry} material={materials['매테리얼.002']} skeleton={nodes.Chloe_head_eyes_L_ball.skeleton} />
          <skinnedMesh scale={100} rotation={[-Math.PI / 2, 0, 0]} castShadow name="Chloe_head_eyes_R_ball" geometry={nodes.Chloe_head_eyes_R_ball.geometry} material={materials['매테리얼.002']} skeleton={nodes.Chloe_head_eyes_R_ball.skeleton} />
          <skinnedMesh scale={100} rotation={[-Math.PI / 2, 0, 0]} castShadow name="Chloe_head_face" geometry={nodes.Chloe_head_face.geometry} material={materials['매테리얼.002']} skeleton={nodes.Chloe_head_face.skeleton} />
          <skinnedMesh scale={100} rotation={[-Math.PI / 2, 0, 0]} castShadow name="Chloe_head_teeth_lower" geometry={nodes.Chloe_head_teeth_lower.geometry} material={materials['lambert1.002']} skeleton={nodes.Chloe_head_teeth_lower.skeleton} />
          <skinnedMesh scale={100} rotation={[-Math.PI / 2, 0, 0]} castShadow name="Chloe_head_teeth_upper" geometry={nodes.Chloe_head_teeth_upper.geometry} material={materials['lambert1.002']} skeleton={nodes.Chloe_head_teeth_upper.skeleton} />
          <skinnedMesh scale={100} rotation={[-Math.PI / 2, 0, 0]} castShadow name="Chloe_head_tongue" geometry={nodes.Chloe_head_tongue.geometry} material={materials['lambert1.002']} skeleton={nodes.Chloe_head_tongue.skeleton} />
        </group>
      </group>
    </group>
  )
}

export default Model

useGLTF.preload('../models/model.gltf')
